### ISSUE TITLE
An Inquiry Regarding How Users Can Access Containers Built Through Blueprint

### ISSUE THREAD

**Issue by zz0350** [Blueprint-uServices/blueprint#173]
I previously reached out to inquire about integrating open-source large models as backends. I have a new query now. I have created a workflow specification file named AgentClient.go. The interfaces in this workflow need to be implemented to communicate with the large model. I have managed to implement the communication functionality with the large model, but I am unsure how to proceed further. I am uncertain about how users should send messages to the container corresponding to AgentClient.go.

Even after successfully compiling the code generated by Blueprint and running it using Docker, I find myself at a loss regarding how to interact with it, similar to the examples provided in your original codebase. In my understanding, as long as external entities can call the methods within the AgentClient.go interface, the implementation should be considered successful. However, I am currently unsure how to initiate it from external sources.

Personally, I perceive the workflow specification file of Blueprint as something akin to the runtime module, essentially an API function interface. Therefore, I believe that additional elements might be required for me to utilize a method from an instance of this interface externally. Could you kindly provide some insights or suggestions on this matter?
[blueprint.zip](https://github.com/Blueprint-uServices/blueprint/files/15129120/blueprint.zip)

**Comment by vaastav** [comment]
So, if I understand correctly then I think your code is basically deploying your client agent as a grpc service. 
If you want to simply test if that works then maybe consider deploying it as a http service and then you can use curl to contact the endpoints exposed by the service.

Otherwise, consider adding a workload generator (example with Sockshop here: https://github.com/Blueprint-uServices/blueprint/blob/main/examples/sockshop/workload/workloadgen/workload.go) to contact your grpc service.
